// Each new term in the Fibonacci sequence is generated by adding the  
// previous two terms. By starting with 1 and 2, the first 10 terms 
// will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not
// exceed four million, find the sum of the even - valued terms.

#pragma once
class Problem2
{
public:
    Problem2();
    ~Problem2();

    void Solution();

private:
    // We want all even Fibonacci's up to this value
    const int MAX_NUMBER = 4000000;

    int TotalSum = 0;
    int LastNumber = 0;
    int NextNumber = 1;
};

